#!/bin/bash
set -euo pipefail

# deploy-setup.sh
# PHASE-1: Deploy setup for HTML Standard on Cloudflare + Anthropic integration

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m'

# Parse arguments
if [[ $# -ne 3 ]]; then
    echo "Usage: $0 <CF_ACCOUNT_ID> <CF_API_TOKEN> <ANTHROPIC_API_KEY>"
    echo ""
    echo "Example:"
    echo "  $0 abc123def456... your_cf_token_here sk-ant-..."
    exit 1
fi

CF_ACCOUNT_ID="$1"
CF_API_TOKEN="$2"
ANTHROPIC_API_KEY="$3"

# Export for use in subcommands
export CF_ACCOUNT_ID CF_API_TOKEN ANTHROPIC_API_KEY

# State tracking
PHASE_STEPS=0
PHASE_COMPLETE=0

log_step() {
    ((PHASE_STEPS++))
    echo -e "${BLUE}[$PHASE_STEPS]${NC} $1"
}

log_success() {
    echo -e "    ${GREEN}✓${NC} $1"
    ((PHASE_COMPLETE++))
}

log_info() {
    echo -e "    ${YELLOW}→${NC} $1"
}

log_error() {
    echo -e "    ${RED}✗${NC} $1"
    return 1
}

trap 'echo -e "\n${RED}Deployment failed at step ${PHASE_STEPS}${NC}"; exit 1' ERR

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE-1 DEPLOYMENT SETUP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ============================================================================
# STEP 1: Validate Credentials
# ============================================================================
log_step "Validating credentials..."

if [[ ! "$CF_ACCOUNT_ID" =~ ^[a-f0-9]{32}$ ]]; then
    log_error "CF_ACCOUNT_ID invalid format"
    exit 1
fi
log_success "CF_ACCOUNT_ID format valid"

if [[ ${#CF_API_TOKEN} -lt 20 ]]; then
    log_error "CF_API_TOKEN too short"
    exit 1
fi
log_success "CF_API_TOKEN length valid"

if [[ ${#ANTHROPIC_API_KEY} -lt 20 ]]; then
    log_error "ANTHROPIC_API_KEY too short"
    exit 1
fi
log_success "ANTHROPIC_API_KEY length valid"

# Test Cloudflare API
log_info "Testing Cloudflare API access..."
CF_TEST=$(curl -s -H "Authorization: Bearer $CF_API_TOKEN" \
    https://api.cloudflare.com/client/v4/accounts/"$CF_ACCOUNT_ID" | jq -r '.success // false')

if [[ "$CF_TEST" == "true" ]]; then
    log_success "Cloudflare API authentication successful"
else
    log_error "Cloudflare API authentication failed"
    exit 1
fi

# Test Anthropic API
log_info "Testing Anthropic API access..."
ANTHROPIC_TEST=$(curl -s -X POST https://api.anthropic.com/v1/messages \
    -H "x-api-key: $ANTHROPIC_API_KEY" \
    -H "anthropic-version: 2023-06-01" \
    -H "content-type: application/json" \
    -d '{"model":"claude-3-5-haiku-20241022","max_tokens":10,"messages":[{"role":"user","content":"ok"}]}' \
    | jq -r '.id // .error.type // "error"')

if [[ "$ANTHROPIC_TEST" != "error" ]] && [[ "$ANTHROPIC_TEST" != "authentication_error" ]]; then
    log_success "Anthropic API authentication successful"
else
    log_error "Anthropic API authentication failed: $ANTHROPIC_TEST"
    exit 1
fi

echo ""

# ============================================================================
# STEP 2: Set up project configuration
# ============================================================================
log_step "Setting up project configuration..."

cd "$SCRIPT_DIR"

# Create deployment config directory
mkdir -p .deployment
log_success "Deployment directory created (.deployment/)"

# Store credentials in secure location (gitignored)
cat > .deployment/.env.credentials << 'EOF'
# Deployment Credentials (DO NOT COMMIT)
# Generated by deploy-setup.sh
EOF

echo "CF_ACCOUNT_ID=$CF_ACCOUNT_ID" >> .deployment/.env.credentials
echo "CF_API_TOKEN=$CF_API_TOKEN" >> .deployment/.env.credentials
echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" >> .deployment/.env.credentials

chmod 600 .deployment/.env.credentials
log_success "Credentials stored in .deployment/.env.credentials (mode 600)"

# Create deployment manifest
cat > .deployment/manifest.json << MANIFEST_EOF
{
  "phase": "PHASE-1",
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "deployed_by": "$(git config user.email || echo 'unknown')",
  "git_commit": "$(git rev-parse HEAD)",
  "git_branch": "$(git rev-parse --abbrev-ref HEAD)",
  "cloudflare": {
    "account_id": "$CF_ACCOUNT_ID",
    "api_version": "v4"
  },
  "anthropic": {
    "api_version": "2023-06-01",
    "models": ["claude-3-5-haiku-20241022", "claude-opus-5"]
  }
}
MANIFEST_EOF

log_success "Deployment manifest created (.deployment/manifest.json)"

echo ""

# ============================================================================
# STEP 3: Create deployment scripts
# ============================================================================
log_step "Creating deployment scripts..."

mkdir -p .deployment/scripts

# Create source environment script
cat > .deployment/scripts/load-env.sh << 'LOAD_ENV_EOF'
#!/bin/bash
# Load deployment environment variables
set -o allexport
source "$(dirname "${BASH_SOURCE[0]}")/../.env.credentials"
set +o allexport
LOAD_ENV_EOF

chmod +x .deployment/scripts/load-env.sh
log_success "Created .deployment/scripts/load-env.sh"

# Create Cloudflare worker bootstrap script
cat > .deployment/scripts/deploy-workers.sh << 'DEPLOY_WORKERS_EOF'
#!/bin/bash
set -euo pipefail

# Load credentials
source "$(dirname "${BASH_SOURCE[0]}")/load-env.sh"

echo "Deploying Cloudflare Workers..."

# Example: Deploy a simple worker for content analysis via Anthropic API
WORKER_NAME="html-standard-api"
WORKER_SCRIPT=$(cat << 'WORKER_CODE'
export default {
  async fetch(request) {
    const apiKey = request.headers.get('x-api-key');
    if (!apiKey) {
      return new Response('Missing x-api-key header', { status: 401 });
    }

    try {
      const data = await request.json();
      const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'x-api-key': apiKey,
          'anthropic-version': '2023-06-01',
          'content-type': 'application/json',
        },
        body: JSON.stringify({
          model: 'claude-3-5-haiku-20241022',
          max_tokens: 1024,
          messages: data.messages || [],
        }),
      });

      return new Response(response.body, {
        status: response.status,
        headers: response.headers,
      });
    } catch (error) {
      return new Response(JSON.stringify({ error: error.message }), {
        status: 500,
        headers: { 'content-type': 'application/json' },
      });
    }
  },
};
WORKER_CODE
)

# Deploy via Cloudflare API
echo "Worker deployment would proceed here (requires npm/wrangler)"
echo "Account ID: $CF_ACCOUNT_ID"
echo "Worker: $WORKER_NAME"
DEPLOY_WORKERS_EOF

chmod +x .deployment/scripts/deploy-workers.sh
log_success "Created .deployment/scripts/deploy-workers.sh"

echo ""

# ============================================================================
# STEP 4: Create GitHub Actions workflow
# ============================================================================
log_step "Setting up CI/CD workflow..."

mkdir -p .github/workflows

cat > .github/workflows/deploy.yml << 'WORKFLOW_EOF'
name: Deploy Phase 1

on:
  push:
    branches:
      - claude/credentials-deployment-setup-09112i
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run verification
        run: bash PHASE-1-SETUP-VERIFICATION.sh
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

  deploy:
    needs: verify
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: bash deploy-setup.sh "$CF_ACCOUNT_ID" "$CF_API_TOKEN" "$ANTHROPIC_API_KEY"
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
WORKFLOW_EOF

log_success "Created .github/workflows/deploy.yml"

echo ""

# ============================================================================
# STEP 5: Update .gitignore
# ============================================================================
log_step "Updating .gitignore..."

if ! grep -q "^\.deployment/\.env\." .gitignore 2>/dev/null; then
    cat >> .gitignore << 'GITIGNORE_EOF'

# Deployment secrets (auto-generated)
.deployment/.env.credentials
.deployment/.env.*.local
GITIGNORE_EOF
    log_success "Added deployment secret patterns to .gitignore"
else
    log_info "Deployment patterns already in .gitignore"
fi

echo ""

# ============================================================================
# STEP 6: Commit changes
# ============================================================================
log_step "Committing deployment setup..."

git add -A
git status --short

COMMIT_MSG=$(cat << 'COMMIT_EOF'
chore: Phase 1 deployment setup

- Add PHASE-1-SETUP-VERIFICATION.sh for credential validation
- Add deploy-setup.sh for deployment automation
- Create .deployment/ directory with manifest and helper scripts
- Add GitHub Actions workflow for CI/CD
- Update .gitignore for secrets protection

Co-Authored-By: Claude Haiku 4.5 <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_015gk4f4RxYsLFZv5BCNQ6VK
COMMIT_EOF
)

git commit -m "$COMMIT_MSG" || log_info "No changes to commit"
log_success "Changes committed"

echo ""

# ============================================================================
# STEP 7: Summary & Next Steps
# ============================================================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE-1 DEPLOYMENT SETUP COMPLETE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}✓ Completed: $PHASE_COMPLETE/$PHASE_STEPS steps${NC}"
echo ""
echo "Deployment artifacts created:"
echo "  • .deployment/manifest.json"
echo "  • .deployment/.env.credentials (600 chmod)"
echo "  • .deployment/scripts/"
echo "  • .github/workflows/deploy.yml"
echo ""
echo "Next steps:"
echo "  1. Push to remote: git push -u origin claude/credentials-deployment-setup-09112i"
echo "  2. Configure GitHub secrets (Settings → Secrets and variables → Actions):"
echo "     - CF_ACCOUNT_ID"
echo "     - CF_API_TOKEN"
echo "     - ANTHROPIC_API_KEY"
echo "  3. Create pull request"
echo "  4. Workflow will validate on push"
echo ""
echo "Local testing:"
echo "  source .deployment/scripts/load-env.sh"
echo "  bash .deployment/scripts/deploy-workers.sh"
echo ""
